config/routes.rb
PonyApp::Application.routes.draw do
  root :to => 'pages#index', as: :home_page
  resources :ponies

end

app/models/pony.rb
class Pony < ActiveRecord::Base
  attr_accessible :color, :kind_of, :name
  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/ponies_controller.rb
class PoniesController < ApplicationController
  def new
    @pony = Pony.new
  end
  def create
    @pony = Pony.create(params[:pony])
    if @pony.save
      redirect_to pony_path(@pony)
    else
      render "new"
    end 
  end
  def show
    @pony = Pony.find(params[:id])
  end
end



  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PonyApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
   <%= yield %>
 </div>

</body>
</html>

app/views/pages/index.html.erb
<div class="hero-unit">
   <h1>I can haz pony?</h1>
   <br>
   <p>
     <%= link_to new_pony_path, :class => "btn btn-primary btn-large" do %>
       <i class="icon-heart icon-white"></i>
       Yes you can!
     <% end -%>
   </p>
 </div>

app/views/ponies/new.html.erb
<h1>New Pony</h1>
 <%= form_for @pony, :url => { :action => "create" } do |f| %>
   <%= f.text_field :name %>
   <%= f.text_field :color %>
   <%= f.select :kind_of, ["earth", "pegasus", "unicorn"], :prompt => "-" %>
   <%= f.submit %>
   <%= @pony.errors.full_messages.each do |msg| %>
   	<div class ="alert alert-error"><%= msg %></div>
  <% end %> 	
 <% end -%>

app/views/ponies/show.html.erb
<h1>Pony Profile for <%= @pony.name %>:</h1>
<div class="well">
	<p><strong>Name:</strong> <%= @pony.name %></p>
  <p><strong>Color:</strong> <%= @pony.color %></p>
  <p><strong>Kind of:</strong> <%= @pony.kind_of %></p>
</div>

<%= link_to "Home", :home_page, :class => "btn" %>